name: test-build-deploy
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Collect Static Files
        run: python manage.py collectstatic --noinput

      - name: Run Lint
        run: flake8 .

      - name: Run Tests
        run: pytest

      - name: Run Tests with Coverage
        run: |
          pytest --cov=my_project --cov-fail-under=80 --cov-config=.coveragerc

  containerize:
    if: github.ref == 'refs/heads/master'
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag meez25/lettings:${{ github.sha }} --build-arg "SECRET_KEY=${{ secrets.SECRET_KEY }}" --build-arg "SENTRY_URL=${{ secrets.SENTRY_URL }}"

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push meez25/lettings:${{ github.sha }}

    - name: Run locally with this command
      run: |
        echo "To run locally, execute: docker pull meez25/lettings:$git_commit_hash && docker run -p 8000:8000 meez25/lettings:$git_commit_hash"
    

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [build-and-test, containerize]
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Render
      run: |
          curl -G \
           -d "key=${{ secrets.RENDER_API_KEY }}" \
           -d "imgURL=docker.io/meez25/lettings:${{ github.sha }}" \
           ${{ secrets.DEPLOY_HOOK }}
