name: test-build-deploy
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Lint
        run: flake8 .

      - name: Run Tests
        run: pytest

  containerize:
    needs: build-and-test
    runs-on: ubuntu-latest
    env:
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag meez25/lettings:${{ github.sha }} --build-arg "SECRET_KEY=${{ secrets.SECRET_KEY }}" --build-arg "SENTRY_URL=${{ secrets.SENTRY_URL }}"
    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push meez25/lettings:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test, containerize]
    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Render
      run: |
        curl -H "Authorization: Bearer ${RENDER_API_KEY}" \
             -H "Content-Type: application/json" \
             -X POST \
             -d '{"webhook": "'${DEPLOY_HOOK}'", "imgURL": "docker.io/meez25/lettings@${{ github.sha }}"}' \
             https://api.render.com/webhooks
