name: test-build-deploy
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Lint
        run: flake8 .

      - name: Run Tests
        run: pytest

  containerize:
    runs-on: ubuntu-latest
    env:
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag meez25/lettings:${{ github.sha }} --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }}
    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        docker push meez25/lettings:${{ github.sha }}
